# Site settings
title: "Pierre Wilmot"
description: "Pierre Wilmot - CV"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Pierre Wilmot"
resume_title:                   "Software Engineer / Video Games & Deep Learning"
resume_contact_email:           "pierre.wilmot@gmail.com"
resume_contact_telephone:       ""
resume_contact_address:         "London - UK"
resume_header_contact_info: ""
resume_header_intro: "<p>I’m a software engineer with a background in video game development. I now have 10 years of programming experience, with skills ranging from low level optimisation to software architecture. I’m doing research in Deep Learning, with a special interest for generative models and their applications in creative industries. I’m also interested in Cryptocurrencies and blockchain technologies.</p><p style='text-align:center;'>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    true
resume_section_products:   	true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/pierre-wilmot/"
  resume_twitter_url:           "https://twitter.com/gheaeckkseqrz"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "https://www.facebook.com/gheaeckkseqrz"
  resume_linkedin_url:          "https://www.linkedin.com/in/pierre-wilmot-83267b61"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://gheaeckkseqrz.wordpress.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-merlot
